### ISSUE TITLE
update 1.20.2

### ISSUE THREAD

**Issue by rufwyll** [JR1811/NeMuelch-hide-body-parts#4]
update mod for fabric 1.20.2 please

**Comment by JR1811** [comment]
Hello,

Thank you for the request.
All _**1.20**_ Minecraft versions _**below 1.20.5**_ are available to download now!
Also check your Fabric Loader, it needs to be 0.14.22 or above, if it hasn't updated for you yet.

https://modrinth.com/mod/hide-body-parts/version/0.0.4-1.20

**Comment by rufwyll** [comment]
> Hello,
> 
> Thank you for the request. All _**1.20**_ Minecraft versions _**below 1.20.5**_ are available to download now! Also check your Fabric Loader, it needs to be 0.14.22 or above, if it hasn't updated for you yet.
> 
> https://modrinth.com/mod/hide-body-parts/version/0.0.4-1.20

Is it impossible to do this on a server? At least with op rights
